//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int GradeValue { get; set; }
        public System.DateTime Date { get; set; }
        public int ColumnId { get; set; }
        public Nullable<int> Isvirtual { get; set; }
    
        public virtual Column Column { get; set; }
    }
}
